import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const Matter = localFont({
  src: [
    {
      path: "../../public/fonts/Matter-Regular.db893963.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/Matter-Medium.2d3e576a.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-tt-hoves",
  display: "swap",
});

const systemMono = {
  variable: "--font-system-mono",
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${Matter.variable} ${systemMono.variable} antialiased`}>
        <div
          className="min-h-screen max-w-[1512px] flex flex-col"
          style={{ scrollBehavior: "smooth" }}
        >
          <Header />
          <main className="flex-1 overflow-x-hidden">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
