import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const Matter = localFont({
  src: [
    {
      path: "../../public/fonts/Matter-Regular.db893963.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Matter-Medium.2d3e576a.ttf",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-matter",
  display: "swap",
});

const systemMono = {
  variable: "--font-system-mono",
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${Matter.variable} ${systemMono.variable} antialiased`}>
        <div
          className="min-h-screen flex flex-col relative"
          style={{ scrollBehavior: "smooth" }}
        >
          {/* Header background */}
          <div
            className="absolute top-0 left-1/2 transform -translate-x-1/2 w-screen h-[70dvh] z-0"
            style={{
              backgroundImage: 'url("/image 11.png")',
              backgroundSize: "cover",
              backgroundRepeat: "no-repeat",
            }}
          />
          <Header />
          <main className="flex-1 overflow-x-hidden relative z-10">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
