import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import HeaderBg from "@/assets/background/header-bg.svg";

const Matter = localFont({
  src: [
    {
      path: "../../public/fonts/Matter-Regular.db893963.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Matter-Medium.2d3e576a.ttf",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-matter",
  display: "swap",
});

const systemMono = {
  variable: "--font-system-mono",
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${Matter.variable} ${systemMono.variable} antialiased`}>
        <div
          className="min-h-screen max-w-[1512px] mx-auto flex flex-col relative"
          style={{ scrollBehavior: "smooth" }}
        >
          {/* Header background */}
          <div className="absolute top-0 left-0 w-full h-[400px] lg:h-[736px] z-0">
            <HeaderBg className="w-full h-full object-cover" />
          </div>
          <Header />
          <main className="flex-1 overflow-x-hidden relative z-10">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
